[package]
name = "engine-grib"
version = "0.4.0"
edition = "2021"

[dependencies]
ds-core = { path = "../core" }
ds-storage = { path = "../storage" }
grib = { version = "0.15", default-features = false, features = ["ccsds-unpack-with-libaec"] }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
arc-swap = "1"
quick_cache = "0.6"
tracing = "0.1"
tokio = { version = "1", features = ["sync"] }
thiserror = "2"
