[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/engine-csv",
    "crates/engine-geojson",
    "crates/engine-geotiff",
    "crates/storage",
    "crates/render",
    "crates/api-edr",
    "crates/api-features",
    "crates/api-wms",
    "crates/api-maps",
    "crates/server",
]
exclude = ["fuzz"]
