[package]
name = "engine-querydata"
version = "0.1.0"
edition = "2021"

[dependencies]
ds-core = { path = "../core" }
chrono = { version = "0.4", features = ["serde"] }
thiserror = "2"
tracing = "0.1"
memmap2 = "0.9"
arc-swap = "1"
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
