//! JMA (Japan Meteorological Agency)'s local descriptors for BUFR

use crate::{Descriptor, Tables};

use super::super::{TableBEntry, TableDEntry, XY};

/// Install JMA local descriptors into the provided tables instance.
pub fn install_jma_descriptors(tables: &mut Tables) {
    for desc in &JMA_DATA_DESCRIPTORS {
        tables.table_b.insert(desc.xy, desc);
    }
    for seq in &JMA_SEQUENCE_DESCRIPTORS {
        tables.table_d.insert(seq.xy, seq);
    }
}

pub static JMA_DATA_DESCRIPTORS: [TableBEntry; 40] = [
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 197 },
        element_name: "jma:作成種類",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 3,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 200 },
        element_name: "jma:府県表示番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 7,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 201 },
        element_name: "jma:地点表示番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 10,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 202 },
        element_name: "jma:機関番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 5,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 203 },
        element_name: "jma:潮位観測地点番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 20,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 210 },
        element_name: "jma:河川番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 80000000,
        bits: 24,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 240 },
        element_name: "jma:震央地名番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 10,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 241 },
        element_name: "jma:震央地名の補助的表現のための地点番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 10,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 1, y: 242 },
        element_name: "jma:電文の種類",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 7,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 2, y: 200 },
        element_name: "jma:潮位観測機器の種類",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 4,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 5, y: 240 },
        element_name: "jma:1次メッシュ緯度番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 7,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 6, y: 240 },
        element_name: "jma:1次メッシュ経度番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 7,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 5, y: 241 },
        element_name: "jma:2次メッシュ緯度番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 4,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 6, y: 241 },
        element_name: "jma:2次メッシュ経度番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 4,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 5, y: 242 },
        element_name: "jma:3次メッシュ緯度番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 4,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 6, y: 242 },
        element_name: "jma:3次メッシュ経度番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 4,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 5, y: 243 },
        element_name: "jma:2分の1地域メッシュ番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 3,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 6, y: 243 },
        element_name: "jma:4分の1地域メッシュ番号",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 3,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 7, y: 200 },
        element_name: "jma:検潮所の固定点（球分体）の標高",
        unit: "m",
        scale: 3,
        reference_value: 0,
        bits: 14,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 7, y: 201 },
        element_name: "jma:検潮所の観測基準面の標高",
        unit: "m",
        scale: 3,
        reference_value: -10000,
        bits: 14,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 8, y: 193 },
        element_name: "jma:要素の修飾",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 7,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 8, y: 194 },
        element_name: "jma:現象の位置の修飾", // （震央は、「震央地名の補助的表現のための地点番号」から方位角の方向の距離で示す位置付近）
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 7,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 8, y: 198 },
        element_name: "jma:震度階級の修飾",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 2,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 8, y: 220 },
        element_name: "jma:潮位データに対する修飾子",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 6,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 8, y: 221 },
        element_name: "jma:潮位平滑化フィルタのカットオフ周期",
        unit: "min",
        scale: 0,
        reference_value: 0,
        bits: 8,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 11, y: 202 },
        element_name: "jma:最大風速（１０分間平均）の風向",
        unit: "degree true",
        scale: 0,
        reference_value: 0,
        bits: 9,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 13, y: 212 },
        element_name: "jma:流域雨量指数（高精度）",
        unit: "Numeric",
        scale: 1,
        reference_value: 0,
        bits: 12,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 20, y: 212 },
        element_name: "jma:自動観測による天気",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 5,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 22, y: 202 },
        element_name: "jma:検潮所の観測基準面に対する潮位",
        unit: "Numeric",
        scale: 3,
        reference_value: -3000,
        bits: 15,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 25, y: 192 },
        element_name: "jma:ウィンドプロファイラデータ品質管理情報",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 8,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 25, y: 216 },
        element_name: "jma:潮位観測機器のサンプリング間隔",
        unit: "s",
        scale: 0,
        reference_value: 0,
        bits: 8,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 25, y: 217 },
        element_name: "jma:潮位観測機器による潮位データの平均時間",
        unit: "s",
        scale: 0,
        reference_value: 0,
        bits: 8,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 25, y: 218 },
        element_name: "jma:検潮所の障害情報識別符",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 5,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 25, y: 219 },
        element_name: "jma:AQC",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 3,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 26, y: 193 },
        element_name: "jma:時",
        unit: "h",
        scale: 0,
        reference_value: 0,
        bits: 5,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 26, y: 194 },
        element_name: "jma:分",
        unit: "min",
        scale: 0,
        reference_value: 0,
        bits: 6,
    },
    TableBEntry {
        xy: XY { x: 31, y: 3 },
        class_name: "Data description operator qualifiers",
        element_name: "Delayed descriptor replication factor",
        scale: 0,
        reference_value: 0,
        unit: "Numeric",
        bits: 8,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 60, y: 1 },
        element_name: "jma:マグニチュード",
        unit: "Numeric",
        scale: 1,
        reference_value: 0,
        bits: 7,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 60, y: 2 },
        element_name: "jma:計測震度",
        unit: "Numeric",
        scale: 1,
        reference_value: 0,
        bits: 7,
    },
    TableBEntry {
        class_name: "jma",
        xy: XY { x: 60, y: 3 },
        element_name: "jma:階級震度（整数部）",
        unit: "Numeric",
        scale: 0,
        reference_value: 0,
        bits: 4,
    },
];

pub static JMA_SEQUENCE_DESCRIPTORS: [TableDEntry; 1] = [TableDEntry {
    xy: XY { x: 1, y: 200 },
    category: "jma",
    title: "JIS X 0410 地域メッシュコード",
    sub_title: "",
    elements: &[
        Descriptor { f: 0, x: 5, y: 240 },
        Descriptor { f: 0, x: 6, y: 240 },
        Descriptor { f: 0, x: 5, y: 241 },
        Descriptor { f: 0, x: 6, y: 241 },
        Descriptor { f: 0, x: 5, y: 242 },
        Descriptor { f: 0, x: 6, y: 242 },
    ],
}];
