[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
ds-core = { path = "../core" }
engine-csv = { path = "../engine-csv" }
engine-geojson = { path = "../engine-geojson" }
engine-geotiff = { path = "../engine-geotiff" }
engine-querydata = { path = "../engine-querydata" }
engine-grib = { path = "../engine-grib" }
api-edr = { path = "../api-edr" }
api-features = { path = "../api-features" }
api-wms = { path = "../api-wms" }
api-maps = { path = "../api-maps" }
api-tiles = { path = "../api-tiles" }
ds-render = { path = "../render" }
arc-swap = "1"
axum = "0.8"
http-body = "1"
prometheus = "0.13"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tower = "0.5"
tower-http = { version = "0.6", features = ["cors", "normalize-path"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
uuid = { version = "1", features = ["v4"] }
