//! Small, independently encoded GRIB2 fixtures for engine regressions.

use std::path::PathBuf;
use std::sync::atomic::{AtomicUsize, Ordering};

fn u32_at(bytes: &mut [u8], offset: usize, value: u32) {
    bytes[offset..offset + 4].copy_from_slice(&value.to_be_bytes());
}

fn section(number: u8, length: usize) -> Vec<u8> {
    let mut bytes = vec![0; length];
    u32_at(&mut bytes, 0, length as u32);
    bytes[4] = number;
    bytes
}

/// Simple packing, 2×2 nodes over [0, 0, 1, 1], Kelvin temperature.
/// `packed` is explicitly supplied in source scan order, not generated by
/// the grid iterator being tested. Reference time is 2026-04-05T00:00Z.
pub fn message(scan: u8, base: f32, packed: [u8; 4], surface: u8, level: u32) -> Vec<u8> {
    let mut s1 = section(1, 21);
    s1[6] = 7; // NCEP centre
    s1[9] = 32; // master table
    s1[11] = 1; // forecast reference time
    s1[12..14].copy_from_slice(&2026u16.to_be_bytes());
    s1[14] = 4;
    s1[15] = 5;
    s1[20] = 1;

    let mut s3 = section(3, 72);
    u32_at(&mut s3, 6, 4);
    s3[14] = 6; // spherical earth
    s3[15..30].fill(255);
    u32_at(&mut s3, 30, 2);
    u32_at(&mut s3, 34, 2);
    u32_at(&mut s3, 42, u32::MAX);
    let westward = scan & 128 != 0;
    let northward = scan & 64 != 0;
    let column_major = scan & 32 != 0;
    let alternating = scan & 16 != 0;
    u32_at(&mut s3, 46, if northward { 0 } else { 1_000_000 });
    u32_at(&mut s3, 50, if westward { 1_000_000 } else { 0 });
    s3[54] = 48;
    let last_north = northward ^ (column_major && alternating);
    let last_east = !westward ^ (!column_major && alternating);
    u32_at(&mut s3, 55, if last_north { 1_000_000 } else { 0 });
    u32_at(&mut s3, 59, if last_east { 1_000_000 } else { 0 });
    u32_at(&mut s3, 63, 1_000_000);
    u32_at(&mut s3, 67, 1_000_000);
    s3[71] = scan;

    let mut s4 = section(4, 34);
    s4[11] = 2; // forecast
    s4[17] = 1; // hours
    s4[22] = surface;
    u32_at(&mut s4, 24, level);
    s4[28..34].fill(255);

    let mut s5 = section(5, 21);
    u32_at(&mut s5, 5, 4);
    s5[11..15].copy_from_slice(&base.to_be_bytes());
    s5[19] = 8; // bits per value; both scale factors are zero
    let mut s6 = section(6, 6);
    s6[5] = 255; // no bitmap
    let mut s7 = section(7, 9);
    s7[5..].copy_from_slice(&packed);

    let mut bytes = b"GRIB\0\0\0\x02\0\0\0\0\0\0\0\0".to_vec();
    for part in [s1, s3, s4, s5, s6, s7] {
        bytes.extend(part);
    }
    bytes.extend(b"7777");
    let length = bytes.len() as u64;
    bytes[8..16].copy_from_slice(&length.to_be_bytes());
    bytes
}

pub struct TestSource {
    pub dir: PathBuf,
}

impl TestSource {
    pub fn new() -> Self {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let dir = std::env::temp_dir().join(format!(
            "meteocore-grib-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir(&dir).unwrap();
        Self { dir }
    }

    pub fn write(&self, name: &str, records: &[(&str, &str, Vec<u8>)], step: u32) {
        let mut data = Vec::new();
        let mut index = String::new();
        for (i, (param, level, bytes)) in records.iter().enumerate() {
            index.push_str(&format!(
                "{}:{}:d=2026040500:{param}:{level}:{step} hour fcst:\n",
                i + 1,
                data.len()
            ));
            data.extend_from_slice(bytes);
        }
        std::fs::write(self.dir.join(format!("{name}.grib2")), data).unwrap();
        std::fs::write(self.dir.join(format!("{name}.idx")), index).unwrap();
    }

    pub fn config(&self) -> ds_core::config::GribConfig {
        serde_json::from_value(serde_json::json!({
            "data_path": self.dir.to_str().unwrap(),
            "index_format": "wgrib2", "index_suffix": ".idx", "grid_cache_mb": 16
        }))
        .unwrap()
    }
}

impl Drop for TestSource {
    fn drop(&mut self) {
        let _ = std::fs::remove_dir_all(&self.dir);
    }
}
